import { Link } from 'react-router-dom';
import { products } from '../data/products';
import ProductGrid from '../components/ProductGrid';

export default function Home(){
  return <>
    <section className="hero"><img src="/assets/osen-hero.png" alt="Osen Luxe model in an Ankara evening dress"/><div className="hero-copy"><p className="eyebrow">The Ìdílé Collection · 2026</p><h1>Rooted in craft.<br/><em>Made for now.</em></h1><p className="hero-sub">Statement occasionwear and accessories, shaped in Lagos for women who arrive with intention.</p><Link className="btn btn-dark" to="/shop">Shop the collection <span>↗</span></Link></div><p className="hero-index">01 / 03</p></section>
    <div className="ticker"><div>ELEGANT&nbsp;&nbsp; ✦ &nbsp;&nbsp;HERITAGE&nbsp;&nbsp; ✦ &nbsp;&nbsp;LUXURY&nbsp;&nbsp; ✦ &nbsp;&nbsp;CRAFTED IN LAGOS&nbsp;&nbsp; ✦ &nbsp;&nbsp;ELEGANT&nbsp;&nbsp; ✦ &nbsp;&nbsp;HERITAGE&nbsp;&nbsp; ✦ &nbsp;&nbsp;LUXURY</div></div>
    <section className="products section-pad"><div className="section-head"><div><p className="eyebrow">Freshly arrived</p><h2>New signatures</h2></div><Link className="mini-link" to="/shop">View all →</Link></div><ProductGrid items={products.slice(0,4)}/><Link className="under-link" to="/shop">View all pieces <span>→</span></Link></section>
    <section className="editorial"><img src="/assets/osen-editorial.png" alt="Osen Luxe editorial campaign"/><div className="editorial-copy"><p className="eyebrow">Occasion, reimagined</p><h2>Dressing that<br/><em>speaks first.</em></h2><p>Confident lines, heritage textiles, and a modern Lagos point of view. Every piece is made for entrances worth remembering.</p><Link className="btn btn-light" to="/collections">Discover the edit <span>↗</span></Link></div></section>
    <section className="categories section-pad"><div className="section-head"><div><p className="eyebrow">Find your statement</p><h2>Shop by world</h2></div></div><div className="category-grid"><Link to="/shop?category=wear" className="category-card"><div className="sheet sheet-dress"></div><span><b>01</b><strong>Occasionwear</strong><em>Explore →</em></span></Link><Link to="/shop?category=bags" className="category-card"><div className="sheet sheet-bag"></div><span><b>02</b><strong>Bags</strong><em>Explore →</em></span></Link><Link to="/shop?category=shoes" className="category-card"><div className="sheet sheet-shoes"></div><span><b>03</b><strong>Shoes</strong><em>Explore →</em></span></Link></div></section>
    <section className="story" id="story"><div className="story-mark">OL</div><div className="story-copy"><p className="eyebrow">The Osen point of view</p><h2>Heritage is not a trend.<br/><em>It is our beginning.</em></h2><p>Osen Luxe pairs Nigerian textile traditions with measured, modern silhouettes. Designed in Lagos in limited runs, each piece honours the hands and stories behind it.</p><Link className="under-link light-link" to="/contact">Meet the atelier <span>→</span></Link></div><div className="story-stat"><strong>Small runs.</strong><p>Thoughtfully made,<br/>never mass produced.</p></div></section>
    <Newsletter/>
  </>;
}

function Newsletter(){return <section className="newsletter"><p className="eyebrow">The Osen list</p><h2>Private previews.<br/><em>First access.</em></h2><form onSubmit={e=>{e.preventDefault();e.currentTarget.querySelector('button').textContent='Welcome to Osen ✓';e.currentTarget.reset()}}><input type="email" placeholder="Email address" aria-label="Email address" required/><button>Join us →</button></form><p className="form-note">By subscribing, you agree to receive Osen Luxe news and offers.</p></section>}
