import { Link, useParams } from 'react-router-dom';
import ProductGrid from '../components/ProductGrid';
import { formatNaira } from '../data/products';
import { useCart } from '../context/CartContext';
import { useCatalog } from '../context/CatalogContext';
import { productImageStyle } from '../utils/productImage';
import NotFound from './NotFound';
import { ArrowUpRight } from '../components/Icons';
export default function Product(){const {id}=useParams();const {products,findProduct,status}=useCatalog();const product=findProduct(id);const {addItem}=useCart();if(!product&&status==='loading')return <div className="catalog-loading" role="status">Loading product…</div>;if(!product)return <NotFound/>;const related=products.filter(p=>p.category===product.category&&p.id!==id).slice(0,3);return <><section className="product-detail"><div className={`detail-image sheet ${product.image||''}`} style={productImageStyle(product)}></div><div className="detail-copy"><p className="eyebrow">{product.label} · {product.badge||'Osen signature'}</p><h1>{product.name}</h1><p className="detail-material">{product.material}</p><strong className="detail-price">{formatNaira(product.price)}</strong><p className="detail-description">{product.description}</p><div className="size-row"><span>Size</span><button className="active">One size</button>{product.category==='wear'&&<><button>UK 10</button><button>UK 12</button></>}</div><button className="detail-add btn btn-dark" onClick={()=>addItem(product.id)}>Add to bag <ArrowUpRight/></button><div className="detail-notes"><p>Complimentary Abuja delivery over ₦250,000</p><p>Made in limited quantities</p><p>Returns accepted within 7 days</p></div></div></section><section className="related section-pad"><p className="eyebrow">You may also like</p><h2>More signatures</h2><ProductGrid items={related} className="product-grid-three"/></section></>}
